esphome:
  name: gtil2sdm630
  includes:
    - gtil2sdm630.h
esp8266:
  board: nodemcu

# Enable Home Assistant API
api:

ota:
  password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "gtil2sdm630 Fallback Hotspot"
    password: "***"

captive_portal:

web_server:
  port: 80

logger:
  baud_rate: 0

uart:
  id: uart_bus
  rx_pin: RX #3
  tx_pin: TX #1
  baud_rate: 9600
  data_bits: 8
  stop_bits: 1
  parity: none
  rx_buffer_size: 54

custom_component:
  lambda: |-
    gtil2sdm630 *uart_data_gtil = new gtil2sdm630(id(uart_bus));
    return {uart_data_gtil};
  components:
  - id: uart_data_gtil

sensor:
- platform: custom
  lambda: |-
    App.register_component(uart_data_gtil);
    gtil2sdm630 *gtil_sensor = (gtil2sdm630*) id(uart_data_gtil);
    return {
        gtil_sensor->ac_setpoint, 
        gtil_sensor->ac_display,  
        gtil_sensor->vgrid,      
        gtil_sensor->vbat,        
        gtil_sensor->dac,       
        gtil_sensor->calibration,
        gtil_sensor->temperature,
        gtil_sensor->sdm630_pa       
    };
  sensors:
  - name: "GTIL2SDM630 AC setpoint"
    unit_of_measurement: "W"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1 
  - name: "GTIL2SDM630 AC display"
    unit_of_measurement: "W"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1 
  - name: "GTIL2SDM630 VGrid"
    unit_of_measurement: "V"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1      
  - name: "GTIL2SDM630 VBat"
    unit_of_measurement: "V"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - name: "GTIL2SDM630 DAC"
  - name: "GTIL2SDM630 Calibration"
  - name: "GTIL2SDM630 Temperature"
    unit_of_measurement: "°C"
  - name: "GTIL2SDM630 SDM630 PA"
    unit_of_measurement: "W"
      
